### ISSUE TITLE
Please update README

### ISSUE THREAD

**Issue by yeskunall** [acerbusace/config#1]
Update `README`, describing what most — if not all — config settings do. Thanks! :stuck_out_tongue_winking_eye:

**Comment by acerbusace** [comment]
There are already comments for the config files. 
Please refer to these commits: 
c091123c6a58e898c98c90d3782b623638289176, 7251aec3a0f50956e892b049b8bf2cacbfa94082, 314c045442adc18baf03e8d22a0a930bb66bbdb5.

**Comment by yeskunall** [comment]
My bad! It'd be better if you could highlight the lines where you made comments, just to make it easier for me. :wink: :+1:
